// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSiparişProjesi_KatmanlıMimari.DataAccess.Context;

#nullable disable

namespace YemekSiparişProjesi_KatmanlıMimari.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250113100613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Cart", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.CartItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DishID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("DishID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ea61a583-f3b8-4c50-95bf-b1e13e9ddd85"),
                            CategoryID = 1,
                            CategoryImage = "Images/appetizers.jpg",
                            CategoryName = "Appetizers",
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 910, DateTimeKind.Local).AddTicks(7538),
                            IsActive = true
                        },
                        new
                        {
                            ID = new Guid("4d291559-e36f-4909-a4e8-41c5758350b7"),
                            CategoryID = 2,
                            CategoryImage = "Images/main_courses.jpg",
                            CategoryName = "Main Courses",
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 911, DateTimeKind.Local).AddTicks(8326),
                            IsActive = true
                        },
                        new
                        {
                            ID = new Guid("f6e6cd13-0656-46fa-805d-d49ccb81644d"),
                            CategoryID = 3,
                            CategoryImage = "Images/desserts.jpg",
                            CategoryName = "Desserts",
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 911, DateTimeKind.Local).AddTicks(8339),
                            IsActive = true
                        },
                        new
                        {
                            ID = new Guid("0b2246c2-5751-46f9-8cbf-20d6faf3defc"),
                            CategoryID = 4,
                            CategoryImage = "Images/beverages.jpg",
                            CategoryName = "Beverages",
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 911, DateTimeKind.Local).AddTicks(8357),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Dish", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID1");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c91b48a0-9de2-49ce-bafa-a01ed4bd79ac"),
                            CategoryID = 1,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(2293),
                            Description = "Sarımsak, zeytinyağı, tuz ve domates ile süslenmiş kızarmış ekmek",
                            DishName = "Bruschetta",
                            ImageUrl = "Images/bruschetta.jpg",
                            IsActive = true,
                            UnitPrice = 25.99m
                        },
                        new
                        {
                            ID = new Guid("c7e71f47-39ce-4686-94a7-517bf53486b7"),
                            CategoryID = 1,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3200),
                            Description = "Geleneksel Türk mercimek çorbası",
                            DishName = "Mercimek Çorbası",
                            ImageUrl = "Images/mercimek_corbasi.jpg",
                            IsActive = true,
                            UnitPrice = 20.99m
                        },
                        new
                        {
                            ID = new Guid("3641f01c-e65e-47ed-8afa-d519530a751b"),
                            CategoryID = 1,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3216),
                            Description = "Çıtır yufka içinde peynirli sigara böreği",
                            DishName = "Sigara Böreği",
                            ImageUrl = "Images/sigara_boregi.jpg",
                            IsActive = true,
                            UnitPrice = 30.99m
                        },
                        new
                        {
                            ID = new Guid("daea1477-3703-4a8b-a76e-0f1b9475bbc9"),
                            CategoryID = 1,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3226),
                            Description = "Nohut püresi, tahin, limon suyu ve zeytinyağı ile hazırlanan meze",
                            DishName = "Humus",
                            ImageUrl = "Images/humus.jpg",
                            IsActive = true,
                            UnitPrice = 22.99m
                        },
                        new
                        {
                            ID = new Guid("6a054276-88fe-4872-85af-1e986166ec90"),
                            CategoryID = 2,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3228),
                            Description = "Baharatlarla harmanlanmış el yapımı ızgara köfte",
                            DishName = "Izgara Köfte",
                            ImageUrl = "Images/izgara_kofte.jpg",
                            IsActive = true,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            ID = new Guid("2f4638d8-8b1b-4179-8c77-50af1de4f259"),
                            CategoryID = 2,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3236),
                            Description = "Geleneksel Türk mantısı, yoğurt ve baharatlı domates sosu ile",
                            DishName = "Mantı",
                            ImageUrl = "Images/manti.jpg",
                            IsActive = true,
                            UnitPrice = 40.99m
                        },
                        new
                        {
                            ID = new Guid("b7af94a5-7a2f-47c2-939c-29832005582a"),
                            CategoryID = 2,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3238),
                            Description = "Marine edilmiş tavuk parçaları, ızgara sebzeler ile servis edilir",
                            DishName = "Tavuk Şiş",
                            ImageUrl = "Images/tavuk_sis.jpg",
                            IsActive = true,
                            UnitPrice = 38.99m
                        },
                        new
                        {
                            ID = new Guid("0dbe40b1-f96e-4056-aaa0-7885812fd966"),
                            CategoryID = 2,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3242),
                            Description = "Zeytinyağlı patlıcan yemeği, domates ve soğan ile",
                            DishName = "İmam Bayıldı",
                            ImageUrl = "Images/imam_bayildi.jpg",
                            IsActive = true,
                            UnitPrice = 35.99m
                        },
                        new
                        {
                            ID = new Guid("a78ca396-c1d5-4f5f-afe6-cf507c75eada"),
                            CategoryID = 3,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3244),
                            Description = "Geleneksel Türk tatlısı, ince yufka katmanları arasında fındık, ceviz ile",
                            DishName = "Baklava",
                            ImageUrl = "Images/baklava.jpg",
                            IsActive = true,
                            UnitPrice = 30.99m
                        },
                        new
                        {
                            ID = new Guid("b3af6c60-bee0-438f-9820-b16806a4a1e7"),
                            CategoryID = 3,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3247),
                            Description = "Fırında pişirilmiş geleneksel Türk sütlü tatlısı",
                            DishName = "Sütlaç",
                            ImageUrl = "Images/sutlac.jpg",
                            IsActive = true,
                            UnitPrice = 25.99m
                        },
                        new
                        {
                            ID = new Guid("458c61b4-7c83-4108-a390-eecf7e7015ad"),
                            CategoryID = 3,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3249),
                            Description = "Karamelize şekerle kaplı muhallebi tatlısı",
                            DishName = "Kazandibi",
                            ImageUrl = "Images/kazandibi.jpg",
                            IsActive = true,
                            UnitPrice = 28.99m
                        },
                        new
                        {
                            ID = new Guid("67ebe0e7-07ee-44c2-8712-aba75befe7b2"),
                            CategoryID = 3,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3253),
                            Description = "Kadayıf ve peynir ile yapılan geleneksel Türk tatlısı",
                            DishName = "Künefe",
                            ImageUrl = "Images/kunefe.jpg",
                            IsActive = true,
                            UnitPrice = 32.99m
                        },
                        new
                        {
                            ID = new Guid("49048b52-2d0d-4455-a9be-b7152e54dde7"),
                            CategoryID = 4,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3255),
                            Description = "Geleneksel Türk kahvesi, lokum ile servis edilir",
                            DishName = "Türk Kahvesi",
                            ImageUrl = "Images/turk_kahvesi.jpg",
                            IsActive = true,
                            UnitPrice = 15.99m
                        },
                        new
                        {
                            ID = new Guid("2ecdd040-4fbe-41dc-90ca-335125a3ea4c"),
                            CategoryID = 4,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3257),
                            Description = "Geleneksel Türk yoğurt içeceği",
                            DishName = "Ayran",
                            ImageUrl = "Images/ayran.jpg",
                            IsActive = true,
                            UnitPrice = 10.99m
                        },
                        new
                        {
                            ID = new Guid("a2f17d3d-74e3-46aa-9427-30e798c64a53"),
                            CategoryID = 4,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3259),
                            Description = "Geleneksel Türk turp içeceği",
                            DishName = "Şalgam Suyu",
                            ImageUrl = "Images/salgam_suyu.jpg",
                            IsActive = true,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            ID = new Guid("e68d2ac8-0cad-4f7a-855b-8bcc351d4b91"),
                            CategoryID = 4,
                            CreateDate = new DateTime(2025, 1, 13, 13, 6, 12, 912, DateTimeKind.Local).AddTicks(3262),
                            Description = "Taze sıkılmış limonata",
                            DishName = "Taze Limonata",
                            ImageUrl = "Images/limonata.jpg",
                            IsActive = true,
                            UnitPrice = 14.99m
                        });
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DishID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID", "DishID");

                    b.HasIndex("DishID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Payment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Cart", b =>
                {
                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.CartItem", b =>
                {
                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Dish", b =>
                {
                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Category", null)
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryID1");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Order", b =>
                {
                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.OrderDetail", b =>
                {
                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Dish", "Dish")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Payment", b =>
                {
                    b.HasOne("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Dish", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("YemekSiparişProjesi_KatmanlıMimari.Entites.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
